version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306

  redis:
    image: redis
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "tail -f /dev/null"
    volumes:
      - .:/src
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - db
      - redis

volumes:
  redis:
  bundle:
  mysqldata:
